// <auto-generated />
using CatalogoMusicas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CatalogoMusicas.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoMusicas.Models.Musica", b =>
                {
                    b.Property<int>("IdMusica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMusica"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Classificacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TotalCurtidas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalReproducoes")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdMusica");

                    b.ToTable("tb_musica");
                });

            modelBuilder.Entity("CatalogoMusicas.Models.Podcast", b =>
                {
                    b.Property<int>("IdPodcast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPodcast"));

                    b.Property<int>("Classificacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TotalCurtidas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalReproducoes")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPodcast");

                    b.ToTable("tb_podcast");
                });
#pragma warning restore 612, 618
        }
    }
}
